# isp-billing-crm/frontend/netlify.toml
[build]
  base = "isp-billing-crm/frontend"
  command = "npm run build"
  publish = "isp-billing-crm/frontend/dist"

[build.environment]
  NODE_VERSION = "20.19.0"

# If you still need to proxy API:
[[redirects]]
  from = "/api/*"
  to = "https://isp-billing-crm.onrender.com/api/:splat"
  status = 200
  force = true

# SPA fallback:
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
